# Generated by Django 4.1.7 on 2025-04-29 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='category',
            field=models.CharField(choices=[('lead', 'Lead'), ('client', 'Client'), ('vendor', 'Vendor'), ('partner', 'Partner'), ('other', 'Other')], default='lead', max_length=20),
        ),
    ]
