name: Django Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DJANGO_DB_NAME: mydb
      DJANGO_DB_USER: myuser
      DJANGO_DB_PASSWORD: mypassword
      DJANGO_DB_HOST: localhost

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo systemctl start mysql
          sudo systemctl enable mysql
          sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';"
          sudo mysql -u root -proot -e "CREATE DATABASE mydb;"
          sudo mysql -u root -proot -e "CREATE USER 'myuser'@'localhost' IDENTIFIED BY 'mypassword';"
          sudo mysql -u root -proot -e "GRANT ALL PRIVILEGES on mydb.* TO 'myuser'@'localhost';"
          sudo mysql -u root -proot -e "FLUSH PRIVILEGES;"

      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          python manage.py migrate

      - name: Run Django Tests
        run: |
          python manage.py test
