name: Django Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DJANGO_DB_ENGINE: django.db.backends.mysql
      DJANGO_DB_NAME: ${{ secrets.DJANGO_DB_NAME }}
      DJANGO_DB_USER: ${{ secrets.DJANGO_DB_USER }}
      DJANGO_DB_PASSWORD: ${{ secrets.DJANGO_DB_PASSWORD }}
      DJANGO_DB_HOST: ${{ secrets.DJANGO_DB_HOST }}
      DJANGO_DB_PORT: 3307

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Start MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.DJANGO_DB_NAME }};" -u${{ secrets.DJANGO_DB_USER }} -p${{ secrets.DJANGO_DB_PASSWORD }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Migrations
        run: python manage.py migrate

      - name: Run Tests
        run: |
          python manage.py test
          

