name: Django Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mydb
          MYSQL_USER: myuser
          MYSQL_PASSWORD: mypassword
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      DJANGO_DB_NAME: mydb
      DJANGO_DB_USER: myuser
      DJANGO_DB_PASSWORD: mypassword
      DJANGO_DB_HOST: 127.0.0.1
      DJANGO_DB_PORT: 3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for MySQL
        run: |
          echo "Waiting for MySQL to be ready..."
          sleep 20

      - name: Grant permissions to myuser
        run: |
          sudo apt-get install -y mysql-client
          mysql -h 127.0.0.1 -u root -proot -e "GRANT ALL PRIVILEGES ON *.* TO 'myuser'@'%' WITH GRANT OPTION;"

      - name: Run migrations
        run: |
          python manage.py migrate

      - name: Run Django Tests
        run: |
          python manage.py test
